logging:
  level:
    org.thymeleaf: TRACE
    org.springframework.web: DEBUG
spring:
  application:
    name: my-system
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  web:
    resources:
      cache:
        period: 0
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/home/yroffin/repo/my-system/backend/.tmp/testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api/data
